---
- hosts: localhost
  connection: local
  
  tasks:
  - name: install htop
    package: 
      name: htop
      
  - name: copy .zshrc file
    copy:
     src: files/zshrc
     dest: /Users/mohamedbhaiyat/.zshrc
     owner: mohamedbhaiyat
     group: mohamedbhaiyat
